### PR TITLE
TAB-9518 Fixed by making thread safe, 'path' field in RestfulServlet

### PR DESCRIPTION
**Pull request by rajnishr002**

### CODE REVIEW

**Comment by GaryWKeim** [comment]
It would have been nice if the original author had written any documentation regarding the use of this class. I believe it was used in a pre-4.x statistics gathering feature that is no longer used. I believe this class can be removed.

**Review by GaryWKeim — CHANGES_REQUESTED** [review]
This class is not used so should be removed.

**Comment by prasantakumar82** [comment]
@rajnishr002 remove the class as it's not being used.

**Comment by rajnishr002** [comment]
> @rajnishr002 remove the class as it's not being used.

Removed

**Review by GaryWKeim — APPROVED** [review]

**Comment by GaryWKeim** [comment]
Make this daggy for main, release/4.4.0 and release/4.4.1.

**Comment by rajnishr002** [comment]
Create daggy PR https://github.com/Terracotta-OSS/dso/pull/162

**Comment by rajnishr002** [comment]
Create daggy PR https://github.com/Terracotta-OSS/dso/pull/162, So closing this PR.

**Pull request closed without merging**
